name: Generate Sitemap

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Generate sitemap
      run: |
        npm init -y
        npm install
        node generate-sitemap.js

    - name: Authenticate using PAT
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.SITEMAP }}@github.com/shiftnerd/pandaawardshow.com.git
        
    - name: Commit sitemap
  run: |
    git config user.name "Sitemap Bot"
    git config user.email "bot@pandaawardshow.com"
    git add sitemap.xml
    git commit -m "Update sitemap.xml" || echo "No changes to commit"
    git push
  env:
    GIT_AUTHOR_NAME: Sitemap Bot
    GIT_AUTHOR_EMAIL: bot@pandaawardshow.com
    GIT_COMMITTER_NAME: Sitemap Bot
    GIT_COMMITTER_EMAIL: bot@pandaawardshow.com
